### ISSUE TITLE
feat: Planet information Structure

### ISSUE THREAD

**Issue by Nannk** [arne-fuchs/edcas-client#3]
Currently, the only methods for getting planet info available in the `client.explorer.systems[index1].body_list[index2]` are `get_name`, `get_signals`, `get_parents`, `get_id`. 

I need planet/object info for the panel in tui.

Simplest solution imo would be vector of tuples: `[ ( String, String ) ]` `[ ( "field name", "value" ) ]`

**Comment by arne-fuchs** [comment]
Resolved in https://github.com/arne-fuchs/edcas-client/commit/e0cdb141102377fa3458b06022020d387b46c9ca
