### ISSUE TITLE
Missing target directory.

### ISSUE THREAD

**Issue by HalJordan** [arne-fuchs/edcas-client#5]
```
~/.games/edcas-client %./start.sh
./start.sh: line 7: ./target/debug/edcas-client: No such file or directory
~/.games/edcas-client %./edcas-client
Log file: "/tmp/edcas-client/2024-05-02-01-44.log"
Journal logs: /home/hal_j/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved Games/Frontier Developments/Elite Dangerous
thread 'main' panicked at src/app/news.rs:26:31:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think something is missing from your files. There's no target directory.

**Comment by arne-fuchs** [comment]
Hey, thanks for opening the issue. Which release did you use or did you build it from main?

**Comment by HalJordan** [comment]
I tried the latest, and building after cloning the git repo.

This is arch, and I had to install the latest version provided as it wasn't already present.

I checked the last few releases, all were missing the target directory, so I summarily purged it from from my system and moved on.

**Comment by arne-fuchs** [comment]
I see you are running it with start.sh
The file is depricated and should be removed. Please execute the binary from project root.

**Comment by arne-fuchs** [comment]
https://github.com/arne-fuchs/edcas-client/commit/065ead289cb2c58bbb7e5ef05fcab3b4964780b0
https://github.com/arne-fuchs/edcas-client/commit/0d29a7a9631884420b1f65137f4ead4859a14035

Removed start.sh and updated the README

**Comment by Nannk** [comment]
The `target/debug/edcas-client` will be created by building the project.

```
archlnv dir: ~/Applications 
➜  git clone https://github.com/arne-fuchs/edcas-client
Cloning into 'edcas-client'...
remote: Enumerating objects: 1833, done.
remote: Counting objects: 100% (541/541), done.
remote: Compressing objects: 100% (187/187), done.
remote: Total 1833 (delta 407), reused 447 (delta 345), pack-reused 1292
Receiving objects: 100% (1833/1833), 15.37 MiB | 11.74 MiB/s, done.
Resolving deltas: 100% (1112/1112), done.

archlnv dir: ~/Applications 
➜  cd edcas-client 

archlnv dir: edcas-client git:  master 
➜  ls target
ls: cannot access 'target': No such file or directory
```
after `cargo build`:
```
...
warning: `edcas-client` (bin "edcas-client") generated 12 warnings (run `cargo fix --bin "edcas-client"` to apply 5 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 46s

archlnv dir: edcas-client git:  master took 1m 46.6s 
➜  ls target  
CACHEDIR.TAG  debug

archlnv dir: edcas-client git:  master 
➜  ls target/debug 
build  deps  edcas-client  edcas-client.d  examples  incremental
```
the `edcas-client` is the executable you need

**Comment by arne-fuchs** [comment]
> I tried the latest, and building after cloning the git repo.
> 
> This is arch, and I had to install the latest version provided as it wasn't already present.
> 
> I checked the last few releases, all were missing the target directory, so I summarily purged it from from my system and moved on.

You downloaded the repo files but not the pre-compiled release files. The start.sh only works if you've actually build the repo. If you want it working either fix your cargo or download the precompiled files (edcas-client-linux.tar.gz) https://github.com/arne-fuchs/edcas-client/releases/tag/0.2.6

For release 0.3.0 you'll need to wait some days though.
