### ISSUE TITLE
Missing build requirement: opener

### ISSUE THREAD

**Issue by HalJordan** [arne-fuchs/edcas-client#6]
```
~/.games/edcas-client %cargo build
Updating crates.io index
error: failed to select a version for `opener`.
... required by package `edcas-client v0.3.0 (/home/hal_j/.games/edcas-client)`
versions that meet the requirements `^0.7.0` (locked to 0.7.0) are: 0.7.0

the package `edcas-client` depends on `opener`, with features: `dbus` but `opener` does not have these features.
It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


failed to select a version for `opener` which could resolve this conflict
cargo build  125.33s user 14.59s system 53% cpu 4:21.97 total
```

Also, the only currently available release of opener is 1.0-2

**Comment by arne-fuchs** [comment]
Hey, can you give me your cargo version?

**Comment by arne-fuchs** [comment]
And also on which os are you running this?

**Comment by HalJordan** [comment]
Arch, installed whatever the latest cargo is from pacman/aur right now.

**Comment by Nannk** [comment]
Let me test this when i get back home.

**Comment by Nannk** [comment]
It builds on latest archlinux with rust installed through package manager (not rustup)

![grafik](https://github.com/arne-fuchs/edcas-client/assets/34575742/3ec16e20-3164-47f5-9da4-4255987deaa8)
![grafik](https://github.com/arne-fuchs/edcas-client/assets/34575742/d2ba46bb-4959-432f-9951-985803c5e230)
![grafik](https://github.com/arne-fuchs/edcas-client/assets/34575742/3b8da915-b897-491e-8ec1-d1ec7cda2f59)
i have cargo 1.77.2.

Latest version of Opener is 0.7.0 though.
https://crates.io/search?q=opener
https://github.com/Seeker14491/opener/tags

If you are trying to install `opener` through aur helper, its the wrong opener: https://aur.archlinux.org/packages/opener

Try to add [latest](https://crates.io/crates/dbus/0.9.7) `dbus` in  `Cargo.toml` as a dependency (https://crates.io/crates/opener/0.7.0/dependencies)

Although i have noticed it builds `libdbus-sys` https://lib.rs/crates/libdbus-sys, which it then shows in build log as `"Compiling dbus v0.9.7"`

Found this: https://blog.illixion.com/2021/10/fix-failed-to-select-a-version-cargo/
try clearing cargo cache by deleting `$HOME/.cargo/registry` then build the project again.

**Comment by arne-fuchs** [comment]
@HalJordan Marked as done. Please setup rust and cargo correctly or use the precompiled binaries in the release tab: https://github.com/arne-fuchs/edcas-client/releases/tag/0.2.6

**Comment by Nannk** [comment]
There is also an aur package.
Its a bit broken, you have to put [this logo](https://github.com/arne-fuchs/edcas-client/blob/master/graphics/logo/edcas_128.png) in the `/usr/share/edcas-client/graphics/logo/edcas_128.png`, otherwise itll crash with :
```
Log file: "/tmp/edcas-client/date-and-time.log"
thread 'main' panicked at src/app/news.rs:26:31:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
or clone the repo, cd in it and run the executable from there.

**Comment by arne-fuchs** [comment]
@Nannk Aur package broken? Is this already fixed with the upcoming release?

**Comment by Nannk** [comment]
> @Nannk Aur package broken? Is this already fixed with the upcoming release?

Yes and no. I cant add the image because its not in the release archive (i probably can, but it would have to download it separately). See the issue https://github.com/arne-fuchs/edcas-client/issues/7 .
