### ISSUE TITLE
bug: Logo not present in the release archive.

### ISSUE THREAD

**Issue by Nannk** [arne-fuchs/edcas-client#7]
Without [this image](https://github.com/arne-fuchs/edcas-client/blob/master/graphics/logo/edcas_128.png) in `/usr/share/edcas-client/graphics/logo/edcas_128.png`  or `./graphics/logo/edcas.png` edcas crashes with: 
```
Log file: "/tmp/edcas-client/date-and-time.log"
thread 'main' panicked at src/app/news.rs:26:31:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The image is not present in the [release archive](https://github.com/arne-fuchs/edcas-client/releases/tag/0.2.6). Please dont forget to add it in the next release.

**Comment by arne-fuchs** [comment]
See https://github.com/arne-fuchs/edcas-client/blob/59cb21b2318578251715cd590f5463eaec47fd6c/create-linux-release.sh#L48
It will be included in the next release

**Comment by Nannk** [comment]
should be fixed with https://github.com/arne-fuchs/edcas-client/commit/43f583cb1d2aeba5ac17e239ae2c44ac03f3263a
