### ISSUE TITLE
Bug: journal_interpreter panics/exits before it finishes uploading journals

### ISSUE THREAD

**Issue by Nannk** [arne-fuchs/edcas-client#8]
[2024-05-14-20-01.log](https://github.com/arne-fuchs/edcas-client/files/15312297/2024-05-14-20-01.log)
[output.txt](https://github.com/arne-fuchs/edcas-client/files/15312298/test.txt)

```
➜  ./target/debug/edcas-client --upload-logs 2> test.txt
Log file: "/tmp/edcas-client/2024-05-14-20-01.log"
in the upload_logs function 
before path
after path
after evm_settings
Uploading 247 logs
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
panicked: receiving on a closed channel
```
Last line is from [cli.rs](https://github.com/Nannk/edcas-client/blob/master/src/cli.rs):29

UPD: its possible, im getting rate-limited

**Comment by arne-fuchs** [comment]
@Nannk Problem still persists with upcoming 0.3.0 release?

**Comment by Nannk** [comment]
I have tried to spamupload again. Seems to work fine.
